---

- name: Create temp folder
  ansible.windows.win_file:
    path: '{{ directory }}\temp'
    state: directory

- name: Download MQ Advanced for Developers
  ansible.windows.win_get_url:
    url: "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqadv/mqadv_dev{{ version }}_windows.zip"
    dest: '{{ directory }}\temp\mq.zip'
    force: no
  tags: download

- name: Unzip MQ 
  community.windows.win_unzip:
    src: '{{ directory }}\temp\mq.zip'
    remote_src: yes
    dest: '{{ directory }}\temp\mqex.zip'
  tags: download