---
- name: Copy fixpack to target
  ansible.builtin.copy:
    src: "{{ fixpack_local }}"
    dest: '/var/{{ fixpack_local | basename }}'
    mode: "0644"

- name: Extract fixpack fom TAR
  ansible.builtin.unarchive:
    src: '/var/{{ fixpack_local | basename }}'
    remote_src: true
    dest: /var

- name: Check if license status file exists
  ansible.builtin.stat:
    path: '/var/MQServer/{{ fixpack_local }}-licensestatus.txt'
  register: license_status

- name: Accept MQ license
  ansible.builtin.shell: >-
    /var/MQServer/mqlicense.sh
    -{{ ibmMqLicence }} >
    /var/MQServer/{{ fixpack_local }}-licensestatus.txt
  changed_when: not license_status.stat.exists