---
- name: Check if MQ is already installed
  ansible.windows.win_shell: Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | sort-object -property DisplayName | Select-Object DisplayName | findstr 'IBM MQ'
  register: is_mq_installed
  failed_when:
    - "'FAIL' in is_mq_installed.stderr"

- name: Silent Install
  ansible.windows.win_command:
    cmd: msiexec /i "{{ directory }}\mq-install\MQServer\MSI\IBM MQ.msi" /l*v C:\install.log /q USEINI="{{ directory }}\mq-install\MQServer\Response.ini" TRANSFORMS="1033.mst"
      AGREETOLICENSE="{{ ibmMqLicence }}" ADDLOCAL="Server"
  when: is_mq_installed.rc == 1

- name: Set MQ environment variable
  ansible.windows.win_command:
    cmd: '".\setmqenv.cmd" -s'
    chdir: C:\Program Files\IBM\MQ\bin
