galaxy_info:
  role_name: uninstallmq
  author: IBM Corp.
  description: Uninstalls IBM MQ from the target machine.
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions: [all]
dependencies: []
